USE sakila; 
-- 1

SELECT cat.name AS category, COUNT(fi.title) AS film_count
FROM film_category AS ca
LEFT JOIN film AS fi 
ON ca.film_id = fi.film_id
JOIN category AS cat 
ON ca.category_id = cat.category_id
GROUP BY cat.name;

-- 2 

SELECT sto.store_id, cit.city AS City, cou.country AS Country
FROM store as sto
JOIN address as adr
ON sto.address_id = adr.address_id
JOIN city as cit
ON adr.city_id = cit.city_id
JOIN country as cou
ON cit.country_id = cou.country_id
GROUP BY store_id;

-- 3
-- total revenue generated by each stores in dollars

SELECT sto.store_id, count(pay.amount) AS total_revenue_$
FROM store as sto
RIGHT JOIN staff as sta
ON sto.store_id = sta.store_id
RIGHT JOIN payment as pay
ON sta.staff_id = pay.staff_id
GROUP BY sto.store_id;

-- 4 

SELECT cat.name AS category, round(AVG(fi.length),1) AS film_duration
FROM film_category AS ca
LEFT JOIN film AS fi 
ON ca.film_id = fi.film_id
JOIN category AS cat 
ON ca.category_id = cat.category_id
GROUP BY cat.name
ORDER BY film_duration DESC;



